AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
